source 'https://rubygems.org' do
  gem 'elastic-apm'
  # gem 'elasticsearch'
  gem 'sinatra'
  gem 'aws-sigv4'

  gem "elasticsearch", path: "../../../elasticsearch"
  gem "elasticsearch-api",  path: "../../../elasticsearch-api"
  gem "elasticsearch-transport", path: "../../../elasticsearch-transport"
end
